media:
  - name: imageSets
    label: Image Sets
    input: src/media/image-sets
    output: image-sets
content:
  - name: sets
    label: Photo Sets
    type: collection
    path: src/content/sets
    filename: "{slug}/index.md"
    fields:
      - { name: title, label: Set Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: photos, label: Photos, type: image, list: true }
