media:
  - name: imageSets
    label: Image Sets
    input: public/image-sets
    output: image-sets
  - name: allPhotos
    label: All Photos
    input: public/all-photos
    output: all-photos
content:
  - name: sets
    label: Photo Sets
    type: collection
    path: src/content/sets
    filename: "{primary}.md"
    fields:
      - name: title
        label: Set Title
        type: string
      - name: date
        label: Date
        type: date
      - name: photos
        label: Photos
        type: image
        list: true
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    filename: "{primary}.md"
    fields:
      - name: title
        label: Set Title
        type: string
      - name: datePublished
        label: Date Published
        type: date
      - name: content
        label: Content
        type: rich-text
        options:
          media: imageSets
  - name: about
    label: About
    type: file
    path: src/content/about
    filename: "about.md"
    fields:
      - name: content
        label: Content
        type: rich-text
        options:
          media: allPHotos
